### ISSUE TITLE
Investigate ARM-TTK functionality

### ISSUE THREAD

**Issue by msha1026** [Azure/benchpress#77]
Investigate ARM-TTK and its similarities to Bicep linter (bicep build). Does ARM-TTK have additional functionality that bicep build does not? Has ARM-TTK been deprecated in favor of bicep build?

Document research so that it can be shared with the team.

**Comment by marclerwick** [comment]
While investigating this I compared the tests that are present in each of the linters (ARM vs bicep). In the documentation for the ARM-TTK: https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/template-test-cases in each case where there is a 1:1 mapping between ARM and bicep it is annotated in the documentation.

For those tests that are not mapped, they appear to be specific to either a JSON spec, or to tests that do not need to be executed against bicep files because the foundation for the test is not present in the bicep format (e.g., "Use correct schema" does not apply to bicep because the schema is not specified in bicep and is properly generated by the bicep transpiler when converting to ARM).

I've come to the conclusion that using the bicep CLI is the appropriate method for linting the bicep files.
