### ISSUE TITLE
Create PR pipeline

### ISSUE THREAD

**Issue by marclerwick** [Azure/benchpress#83]
This is essentially a sub-task of a larger "Create CI/CD Pipeline" user story.

The focus of this user story is to create the portion of the CI/CD pipeline that will prepare the code for CI when a Pull Request is submitted. The following are requirements of the pipeline when a PR is submitted:

- [x] A minimum of two reviewer must accept the changes before any subsequent steps in the CI/CD pipeline can occur.
- [ ] Linting executed against any Markdown files and any code files with linters specific to the coding language - failures will prevent any subsequent steps in the CI/CD pipeline.
- [ ] PowerShell Script Analyzer executed against all PowerShell scripts.

**Comment by msha1026** [comment]
Update: this Issue is semi-blocked as some of the linting errors have to do with naming conventions of our cmdlets. There also needs to be a decision made on whether to use an "all-in-one" linter like megalinter, or to call out each language linter ourselves in the Github Action. These topics will be discussed during 1/12 design session. In the meantime, will try and fix as many linting issues as possible.
