### ISSUE TITLE
Step through GitHub wiki and document what needs to be transferred to developer docs

### ISSUE THREAD

**Issue by msha1026** [Azure/benchpress#97]
As an engineer, I would like to walkthrough the Github Wiki and document what important information needs to be moved to developer docs in the repository, so that crucial learnings can be shared to contributors and consumers of BenchPress.

- [ ] Follow up issues are created for developer docs that need to be created from the Github Wiki

**Comment by ozboms** [comment]
Task done by putting Wiki recommendations in the the [architecture documentation](https://github.com/orgs/Azure/projects/313/views/1?pane=issue&itemId=18732857) issue.

Do not think that each Wiki section needs to have a separate document since most of the information in there is spikes; and we've made choices from those spikes for architrecture.
